version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      owncloud-web-monorepo:
        patterns:
          - '@ownclouders/extension-sdk'
          - '@ownclouders/web-test-helpers'
          - '@ownclouders/web-client'
          - '@ownclouders/web-pkg'
          - '@ownclouders/eslint-config'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
