importer:
  config:
    companionUrl: 'https://host.docker.internal:9200/companion'

ai-quick-draft-creator:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

ai-doc-summary:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

ai-image-alt-text-sidebar:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llava:7b'

chat-with-file:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

version-changelog:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

ai-folder-brief-sidebar:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

ai-sensitive-data-scanner:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

ai-data-insights-sidebar:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

ai-multi-doc-synthesizer:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'

ai-smart-file-tagger-qa:
  config:
    llm:
      endpoint: 'https://host.docker.internal:9200/ai-llm-proxy/v1'
      model: 'llama3.2'
